import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#8ff5ff",
        "surface-bright": "#1f2b49",
        background: "#060e20",
        "surface-container-lowest": "#000000",
        "on-error": "#490006",
        surface: "#060e20",
        "on-secondary-fixed-variant": "#515c70",
        "on-secondary-container": "#c5d1e8",
        "tertiary-fixed": "#7bd1fa",
        "tertiary-container": "#7bd1fa",
        "primary-fixed-dim": "#00deec",
        "secondary-fixed": "#d8e3fb",
        outline: "#6d758c",
        "primary-container": "#00eefc",
        "on-primary-fixed-variant": "#005e64",
        "on-surface": "#dee5ff",
        "on-tertiary-container": "#00465d",
        "on-primary-fixed": "#003f43",
        "on-tertiary-fixed-variant": "#004f69",
        "on-tertiary-fixed": "#003041",
        "secondary-container": "#3c475a",
        secondary: "#d8e3fb",
        "on-background": "#dee5ff",
        "surface-container-high": "#141f38",
        "on-primary": "#005d63",
        "on-surface-variant": "#a3aac4",
        "tertiary-fixed-dim": "#6cc3eb",
        "on-primary-container": "#005359",
        "surface-tint": "#8ff5ff",
        "inverse-on-surface": "#4d556b",
        error: "#ff716c",
        "inverse-surface": "#faf8ff",
        "error-container": "#9f0519",
        "secondary-dim": "#cad5ed",
        "error-dim": "#d7383b",
        "surface-variant": "#192540",
        "on-tertiary": "#004f69",
        "inverse-primary": "#006a71",
        "on-secondary-fixed": "#354053",
        "on-secondary": "#475266",
        "surface-container-highest": "#192540",
        "outline-variant": "#40485d",
        tertiary: "#9bddff",
        "primary-fixed": "#00eefc",
        "tertiary-dim": "#6cc3eb",
        "primary-dim": "#00deec",
        "surface-container": "#0f1930",
        "surface-dim": "#060e20",
        "secondary-fixed-dim": "#cad5ed",
        "on-error-container": "#ffa8a3",
        "surface-container-low": "#091328",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      animation: {
        "spin-slow": "spin 10s linear infinite",
      },
    },
  },
  plugins: [forms],
};
